//  fetchLeverageBalances
export const LEVERAGE_FETCH_LEVERAGE_BALANCES_BEGIN = 'LEVERAGE_FETCH_LEVERAGE_BALANCES_BEGIN';
export const LEVERAGE_FETCH_LEVERAGE_BALANCES_SUCCESS = 'LEVERAGE_FETCH_LEVERAGE_BALANCES_SUCCESS';
export const LEVERAGE_FETCH_LEVERAGE_BALANCES_FAILURE = 'LEVERAGE_FETCH_LEVERAGE_BALANCES_FAILURE';
// fetchPoolsData
export const LEVERAGE_FETCH_POOLS_DATA_BEGIN = 'LEVERAGE_FETCH_POOLS_DATA_BEGIN';
export const LEVERAGE_FETCH_POOLS_DATA_SUCCESS = 'LEVERAGE_FETCH_POOLS_DATA_SUCCESS';
export const LEVERAGE_FETCH_POOLS_DATA_FAILURE = 'LEVERAGE_FETCH_POOLS_DATA_FAILURE';